// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TestPattern } from "./TestPattern";
import type { WhiteBalanceMode } from "./WhiteBalanceMode";

export type CameraProperties = { exposure_time?: number, gain?: number, brightness?: number, contrast?: number, saturation?: number, sharpness?: number, auto_white_balance?: boolean, white_balance_mode?: WhiteBalanceMode, color_gain_red?: number, color_gain_blue?: number, test_pattern?: TestPattern, };
