// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComputeNodeCapabilities } from "./ComputeNodeCapabilities";

export type ComputeNode = { node_id: string, capabilities: ComputeNodeCapabilities, };
