// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Procedure } from "./Procedure";

export type ComputeNodeCapabilities = { procedures: { [key in string]?: Procedure }, };
