// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProcedureUi } from "./ProcedureUi";

export type ComputeNodeCapabilities = { procedures: { [key in string]?: ProcedureUi }, };
