// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ElementPositioning } from "./ElementPositioning";

export type Element = { "Image": { display_name: string, href: string, positioning: ElementPositioning, } } | { "Select": { display_name: string, options: Array<string>, value: string, positioning: ElementPositioning, } } | { "Button": { display_name: string, positioning: ElementPositioning, } } | { "Slider": { display_name: string, min: number, max: number, step: number, value: number, positioning: ElementPositioning, } };
