// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ElementPositioning } from "./ElementPositioning";

export type Element = { "type": "image", display_name: string, href: string, positioning: ElementPositioning, } | { "type": "select", display_name: string, options: Array<string>, value: string, positioning: ElementPositioning, } | { "type": "button", display_name: string, positioning: ElementPositioning, } | { "type": "slider", display_name: string, min: number, max: number, step: number, value: number, positioning: ElementPositioning, };
