// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Input = { "Selection": { display_name: string, options: Array<string>, value: string, } } | { "ImagePreview": { display_name: string, href: string, } };
