// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Input } from "./Input";
import type { Output } from "./Output";

export type Procedure = { display_name: string, description: string, inputs: { [key in string]?: Input }, outputs: { [key in string]?: Output }, };
