// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Widget } from "./Widget";

export type ProcedureUiDescription = { name: string, display_name: string, description: string, columns: number, progress: number | null, locked: boolean, elements: { [key in string]?: Widget }, };
