// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComputeNode } from "./ComputeNode";
import type { ComputeNodeCapabilities } from "./ComputeNodeCapabilities";
import type { LogEntry } from "./LogEntry";
import type { Parameters } from "./Parameters";
import type { ProcedureUi } from "./ProcedureUi";
import type { Value } from "./Value";

export type WebSocketMessage = "register_user_client" | { "register_compute_node": ComputeNodeCapabilities } | { "update_parameters": Parameters } | { "compute_nodes": Array<ComputeNode> } | { "with_procedure_params": { procedure_name: string, source_uuid: string | null, destination_uuid: string, params: { [key in string]?: Value }, } } | { "procedure_description": { procedure_name: string, destination_uuid: string, procedure: ProcedureUi, } } | { "logs": Array<LogEntry> };
