// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComputeNodeCapabilities } from "./ComputeNodeCapabilities";
import type { LogEntry } from "./LogEntry";
import type { Parameters } from "./Parameters";

export type WebSocketMessage = "register_user_client" | { "register_compute_node": ComputeNodeCapabilities } | { "update_parameters": Parameters } | { "logs": Array<LogEntry> };
