// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WidgetPosition } from "./WidgetPosition";

export type Widget = { "type": "image", display_name: string, href: string, positioning: WidgetPosition, } | { "type": "select", display_name: string, options: Array<string>, value: string, positioning: WidgetPosition, } | { "type": "button", display_name: string, positioning: WidgetPosition, } | { "type": "slider", display_name: string, min: number, max: number, step: number, value: number, positioning: WidgetPosition, };
