// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ZScanMetadata = { relative_start_pos: number, relative_stop_pos: number, steps_between_layers: number, frame_count: number, uuid: string, timestamp: string, };
